# global:
#   scrape_interval:     15s 
#   evaluation_interval: 15s 

# scrape_configs:
#   - job_name: 'nestjs'
#     metrics_path: '/api/metrics' 
#     scheme: http
#     static_configs:
#       - targets: ['nestjs:3000'] 
#       # - targets: ['host.docker.internal:3000'] 
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'nestjs-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prometheus:9090', 'host.docker.internal:3005']
  - job_name: 'node-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
